#!/usr/bin/env bun
import { getVirtualizationWorkload } from '@pierre/tree-test-data';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve as resolvePath } from 'node:path';
import { gzipSync } from 'node:zlib';

import {
  AOSP_PREVIEW_PATHS,
  AOSP_TOTAL_PATH_COUNT,
} from '../app/trees-dev/_lib/aospPreview';
import {
  BULK_EXPERIMENT_WORKLOAD_NAMES,
  BULK_PREVIEW_PATH_COUNT,
} from '../app/trees-dev/_lib/bulkExperimentMeta';
import { deriveAllExpandedPaths } from '../app/trees-dev/_lib/deriveAllExpandedPaths';
import { AOSP_UPGRADE_DATA_URL } from '../app/trees-dev/_lib/workloadMeta';

interface GeneratedPreviewEntry {
  previewPaths: readonly string[];
  totalPathCount: number;
}

const repoRoot = resolvePath(import.meta.dirname, '../../..');
const outputDir = resolvePath(repoRoot, 'apps/docs/public/trees-dev');
const previewOutputPath = resolvePath(
  repoRoot,
  'apps/docs/app/trees-dev/_lib/bulkExperimentPreviewData.ts'
);

const previewEntries: Record<string, GeneratedPreviewEntry> = {};
mkdirSync(outputDir, { recursive: true });

for (const workloadName of BULK_EXPERIMENT_WORKLOAD_NAMES) {
  if (workloadName === 'aosp') {
    previewEntries[workloadName] = {
      previewPaths: AOSP_PREVIEW_PATHS.slice(0, BULK_PREVIEW_PATH_COUNT),
      totalPathCount: AOSP_TOTAL_PATH_COUNT,
    };
    console.log(`[bulk] aosp preview reuses ${AOSP_UPGRADE_DATA_URL}`);
    continue;
  }

  const workload = getVirtualizationWorkload(workloadName);
  const allExpandedPaths = deriveAllExpandedPaths(workload.presortedFiles);
  const payload = JSON.stringify({
    allExpandedPaths,
    paths: workload.presortedFiles,
  });
  const gz = gzipSync(payload, { level: 9 });
  const outputPath = resolvePath(outputDir, `${workloadName}.json.gz`);
  writeFileSync(outputPath, gz);

  previewEntries[workloadName] = {
    previewPaths: workload.presortedFiles.slice(0, BULK_PREVIEW_PATH_COUNT),
    totalPathCount: workload.presortedFiles.length,
  };

  console.log(
    `[bulk] ${workloadName} → ${outputPath} (${(gz.byteLength / 1024 / 1024).toFixed(1)} MB, from ${(payload.length / 1024 / 1024).toFixed(1)} MB)`
  );
}

const previewContent = `// Generated by apps/docs/scripts/generateBulkExperimentArtifacts.ts. Do not edit by hand.
import type { BulkExperimentWorkloadName } from './bulkExperimentMeta';

export interface BulkExperimentPreviewData {
  previewPaths: readonly string[];
  totalPathCount: number;
}

export const BULK_EXPERIMENT_PREVIEW_DATA = ${JSON.stringify(previewEntries, null, 2)} satisfies Record<BulkExperimentWorkloadName, BulkExperimentPreviewData>;
`;

writeFileSync(previewOutputPath, previewContent, 'utf8');
console.log(`[bulk] preview data → ${previewOutputPath}`);
